### PR TITLE
Use the most recent version of bgpdump, update CDefs accordingly

### PR DESCRIPTION
**Pull request by Rafiot**
Also: break python 2.7 compat.

### CODE REVIEW

**Comment by Rafiot** [comment]
I'm not sure you're interested in merging that, as it doesn't cares about backward compatibility, but I wanted to share before I add more breaking changes to integrate it with an other existing tool.

**Comment by alexforster** [comment]
Cool! I'll check it out this weekend.

**Comment by Rafiot** [comment]
I did a lot more messing around and now use it in production here: https://github.com/D4-project/IPASN-History/blob/master/ipasnhistory/ripe_loader.py#L56

It seems to work fine, but I only use a subset of the functionalities. 

And thank you very much for the bindings, they're super useful!

**Comment by alexforster** [comment]
I'm closing this in favor of #4, where I think I've made all your changes while also keeping Py2 and Py3 compatibility. Let me know if you see any changes that you needed and I missed. I intend to publish macOS and Linux Py2/Py3 wheels for this release.

**Pull request closed without merging**
